name: 'Build, Lint, Test'

on:
    pull_request:
        types: [opened, reopened, ready_for_review, synchronize]

jobs:
    build:
        name: Pull request
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: yarn ci
              timeout-minutes: 15

            - name: Running tests
              run: yarn test
              timeout-minutes: 15

            - name: Running lint
              run: yarn lint
              timeout-minutes: 15
